export const ENGAGE_EXTENSION_ACTION = {
  runScan: 'engage:scan',
  runMetrics: 'engage:metrics',
  scanXKeyword: 'engage:scan-x-keyword',
  fetchXPost: 'engage:fetch-x-post',
  scanXAccount: 'engage:scan-x-account',
  scanRedditKeyword: 'engage:scan-reddit-keyword',
  fetchRedditPost: 'engage:fetch-reddit-post',
  scanRedditUser: 'engage:scan-reddit-user',
  fetchReplyMetrics: 'engage:fetch-reply-metrics',
  fetchPostMetrics: 'posts:fetch-metrics',
  ingestCollectedPosts: 'engage:ingest-collected-posts',
  syncCollectedMetrics: 'engage:sync-collected-metrics',
  loadConfig: 'engage:load-config',
  socialSessions: 'social:sessions',
  publishEnqueue: 'publish:enqueue',
  publishCancel: 'publish:cancel',
  publishStatus: 'publish:status',
  /** SW → content-script push forwarded to the page as postPublishProgress. */
  publishProgressPush: 'publish:progress-push',
  loadSubscription: 'user:load-subscription',
  claimTasks: 'engage:claim-tasks',
  executeTask: 'engage:execute-task',
  releaseTask: 'engage:release-task',
  ingestTask: 'engage:ingest-task',
} as const;
