// Browser-page X collection helpers used by the extension Options page. They use
// "open background tab → let x.com fire its OWN GraphQL → intercept the response"
// path end-to-end, WITHOUT any backend/server call, so the tab+interceptor
// mechanism can be validated in a real browser.
//
//   scanXKeywordFromPage(kw) → x.com/search?q=kw&f=live → capture SearchTimeline
//   fetchXPostFromPage(id)   → x.com/i/web/status/<id> → capture TweetDetail
//
// Requires the user to be logged into x.com and the document-start interceptor
// (x-capture.ts) to be active (registered via the manifest content_script).

import { ParsedTweet, parseTimelineTweets } from './x.parse';
import { openXReadTab, readViaProfile, readXOnce } from './x.tab-reader';
import { parseSearchList } from './scan.x';

// Kept as a compatibility export for existing parser tests and debug callers.
// The implementation lives in the production scanner so parsing cannot fork.
export { parseSearchList };

/** TweetDetail `data` → the focal tweet (matching id, else the first). */
export function parseTweetDetailFocal(
  data: any,
  id: string
): ParsedTweet | null {
  const instructions =
    data?.threaded_conversation_with_injections_v2?.instructions ?? [];
  const all = parseTimelineTweets(instructions);
  return all.find((t) => t.id === id) ?? all[0] ?? null;
}

/** Extract a numeric tweet id from a raw id or any X status URL. */
export function extractTweetId(input: string): string {
  const s = String(input || '').trim();
  const m = s.match(/status(?:es)?\/(\d+)/) || s.match(/(\d{6,})/);
  return m ? m[1] : s.replace(/\D/g, '');
}

/** Keyword search via X's own SearchTimeline (Latest tab). */
export async function scanXKeywordFromPage(
  keyword: string
): Promise<ParsedTweet[]> {
  const kw = String(keyword || '').trim();
  if (!kw) return [];
  const session = await openXReadTab();
  if (!session) throw new Error('Could not open a background x.com tab');
  try {
    const url =
      'https://x.com/search?q=' +
      encodeURIComponent(kw) +
      '&f=live&src=typed_query';
    const resp = await session.navigateAndCapture(url, 'SearchTimeline');
    if (resp == null) return [];
    const data = (resp as { data?: unknown }).data ?? resp;
    return parseSearchList(data);
  } finally {
    await session.close();
  }
}

/**
 * Combined account + keywords search: `from:account (kw1 OR kw2)`.
 *
 * Opens a real x.com background tab so X's own JavaScript fires the
 * SearchTimeline request — the request carries authentic fingerprints
 * (x-client-transaction-id, proper sec-fetch-* headers, same-origin context)
 * generated by X's own code, not a synthetic service-worker call.
 *
 * Two-step navigation for a realistic browsing chain:
 *   1. Visit the account's profile page (seeds tab history + HTTP Referer).
 *   2. Navigate to the search URL via in-page script so the browser
 *      carries Referer: profile URL in the page request.
 *
 * @param account   X handle, with or without leading `@`
 * @param keywords  One or more keywords; phrases are auto-quoted
 */
export async function scanXAccountFromPage(
  account: string,
  keywords: string[]
): Promise<ParsedTweet[]> {
  const handle = account.replace(/^@/, '').trim();
  if (!handle) throw new Error('account is required');
  const active = keywords.map((k) => k.trim()).filter(Boolean);
  if (!active.length) throw new Error('at least one keyword is required');

  const kwClause = active
    .map((k) => (k.includes(' ') ? `"${k}"` : k))
    .join(' OR ');
  const rawQuery = `from:${handle} (${kwClause})`;

  const profileUrl = `https://x.com/${handle}`;
  // Use the default Top tab (no &f=live) — account-scoped searches cover
  // all time rather than just recent posts, so Top returns relevant results
  // where Latest often returns 0 for low-frequency accounts.
  const searchUrl =
    'https://x.com/search?q=' +
    encodeURIComponent(rawQuery) +
    '&src=typed_query';

  // keepOpen defaults to false — the tab closes after a natural linger delay
  // (1.5-3 s) so the session duration doesn't look like an instant bot hit.
  const resp = await readViaProfile(profileUrl, searchUrl, 'SearchTimeline');
  if (resp == null) return [];
  const data = (resp as { data?: unknown }).data ?? resp;
  return parseSearchList(data);
}

/** Fetch a single tweet's data via X's own TweetDetail (status page). */
export async function fetchXPostFromPage(
  idOrUrl: string
): Promise<ParsedTweet | null> {
  const id = extractTweetId(idOrUrl);
  if (!id) return null;
  const resp = await readXOnce(
    'https://x.com/i/web/status/' + id,
    'TweetDetail'
  );
  if (resp == null) return null;
  const data = (resp as { data?: unknown }).data ?? resp;
  return parseTweetDetailFocal(data, id);
}
