-- Out-of-band database objects that `prisma db push` cannot create.
--
-- This file used to own the trigram INDEXES as well. It no longer does: they are
-- declared in schema.prisma (EngageOpportunity, `ops: raw("gin_trgm_ops")` +
-- `type: Gin`), which Prisma 6 supports without a preview feature.
--
-- Moving them was a correctness fix, not tidying. `db push` DROPS any index the
-- schema does not know about, so while they lived only here every push deleted
-- them, and the `&& prisma-db-indexes` half of the "prisma-db-push" npm script
-- was the only thing putting them back. Anyone who ran the push on its own was
-- left with a sequential scan over the GLOBAL (cross-org, unbounded)
-- EngageOpportunity table on every keyword preview — no error, just slow. The
-- schema declarations carry `map:` so they adopt the names created here, which
-- is why existing databases needed no index rebuild.
--
-- What remains here is the one thing a schema cannot express without the
-- postgresqlExtensions preview feature: the EXTENSION itself. An index
-- referencing gin_trgm_ops cannot be created before it exists, so this must
-- still run BEFORE a push against a fresh database.
--
-- Still wired into the "prisma-db-push" npm script. Idempotent.

CREATE EXTENSION IF NOT EXISTS pg_trgm;
